[build-system]
requires = [
    "setuptools>=41.0",
    "wheel>=0.33",
    "setuptools_scm[toml]>=6.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "openmm_dlext"
version = "0.2.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version>="3.7"',
]
